### ISSUE TITLE
前端websocket服务器传递的数据添加参数 interviewID

### ISSUE THREAD

**Issue by MouseHappy123** [scutcs3/codeview#111]
目前三种情况的后台接收数据
接受到: {"username":"VieweeID","input":"sadsad","Ischat":1,"chatnum":0}
接受到: {"username":"ViewerID","value":"a","language":"cpp","theme":"vs","IsCode":1}
接受到: {"title":"三全鲜食（北新泾店）","content":"长宁区新渔路144号","IsPorblem":1}
预期在这三种接收数据中添加interviewID参数，类型为数字，获取方式如下：
```
 import hashids from "hashids";

   let hash = new hashids("codeview salt", 16);
   interview_id = hash.decode(this.$route.query.hashid);
//会通过interviewListPage.vue下的router-link传递hashid，在viewerPage和vieweePage里可以通过上述代码获取面试id
````

**Comment by DD20-dai** [comment]
对就是这三个
