### ISSUE TITLE
编译器代码同步

### ISSUE THREAD

**Issue by DD20-dai** [scutcs3/codeview#81]
预计先实现好面试者提交代码，面试官这边能看到提交的代码。
实现完后再考虑面试官或者面试者其中一方写代码的时候另一方编译器中能够实时同步对方的代码

**Comment by tootal** [comment]
详细描述一下这个需求。

**Comment by DD20-dai** [comment]
> 详细描述一下这个需求。

收到！

**Comment by tootal** [comment]
这个应该是扩展内容吧？目前要先实现必须的功能，就是面试者提交代码，面试官这边能看到提交的代码就行了。

**Comment by DD20-dai** [comment]
> 这个应该是扩展内容吧？目前要先实现必须的功能，就是面试者提交代码，面试官这边能看到提交的代码就行了。

OKOK  我先实现面试者提交代码然后面试官这边能看到代码
