### ISSUE TITLE
面试id生成

### ISSUE THREAD

**Issue by tootal** [scutcs3/codeview#87]
目前的面试id是直接使用数据库递增的id，与“获得面试链接的人即可参与聊天”需求结合会产生安全风险（意味着可以随机进入其它面试来聊天）。因此需要一种新的面试id方案，需要满足以下特点：

* 唯一。不同面试要有不同的id。
* 简短。面试id要用在url中用于分享，不能太长。
* 不可枚举。无法通过简单的规律遍历所有id。
* 生成算法简单通用，易于实现。

**Comment by MouseHappy123** [comment]
https://github.com/muhammadghazali/hashids.node.js
